language: generic
sudo: required

services:
    - docker

before_install:
    - docker build -t tyler/whatsapp-clone -f Dockerfile.dev .

script:
    - docker run -e CI=true tyler/whatsapp-clone npm run test

after_success:
    - docker build -t tyler/whatsapp-clone .
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    -docker push tyler/whatsapp-clone