language: node_js

node_js:
    - 'node'

services:
    - docker

jobs:
    include:
        - stage: test
          script:
            - npm install
        - stage: docker-deploy-image
          script:
            - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
            - docker build -t $DOCKER_USER/whatsapp-clone .
            - docker push $DOCKER_USER/whatsapp-clone
        - stage: deploy
          script: skip
#          deploy: 
#            provider: elasticbeanstalk
#            acces_key_id: $AWS_ACCESS_KEY_ID
#            secret_access_key: $AWS_SECRET_ACCESS_KEY
#            region: 'us-west-1'
#            app: 'WhatsApp Clone'
#            env: 'WhatsappClone-env-1'
#           bucket_name: 'elasticbeanstalk-us-west-1-221103962736'
#            bucket_path: 'WhatsApp Clone'